# Generated by Django 5.2.9 on 2025-12-03 16:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gatepass_number',
            field=models.CharField(blank=True, help_text='Gatepass/Access Card Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ot_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Overtime rate per hour', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Daily salary amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='uan_number',
            field=models.CharField(blank=True, help_text='Universal Account Number (PF)', max_length=20, null=True),
        ),
    ]
