# Generated by Django 5.2.9 on 2025-12-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0002_employee_gatepass_number_employee_ot_per_hour_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company'], name='employees_company_c5d415_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='employees_is_acti_e91717_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_code'], name='employees_employe_6fc092_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'is_active'], name='employees_company_93e915_idx'),
        ),
    ]
