# Generated by Django 5.2.9 on 2025-12-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_employees_company_c5d415_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ot_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overtime rate per hour', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily salary amount', max_digits=10, null=True),
        ),
    ]
