# Generated by Django 5.2.9 on 2025-12-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_ot_per_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number for attendance notifications (e.g., +919876543210)', max_length=20, null=True),
        ),
    ]
