# Generated by Django 5.2.9 on 2025-12-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_mobile_passwordresetotp'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_companies',
            field=models.ManyToManyField(blank=True, help_text='Companies this supervisor can manage attendance for', related_name='supervisors', to='companies.company'),
        ),
    ]
