# Generated by Django 5.2.9 on 2025-12-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_assigned_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_past_date',
            field=models.DateField(blank=True, help_text='Specific past date supervisor is allowed to mark attendance for', null=True),
        ),
    ]
