# Generated by Django 5.2.9 on 2025-12-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_allowed_past_date'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number for notifications', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='assigned_companies',
            field=models.ManyToManyField(blank=True, help_text='Companies this user can manage (for admin/supervisor)', related_name='assigned_users', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('SUPERVISOR', 'Supervisor')], default='SUPERVISOR', max_length=20),
        ),
    ]
