# Generated by Django 5.2.9 on 2025-12-03 17:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='has_ot',
            field=models.BooleanField(default=False, help_text='Did employee work overtime?'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='ot_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Number of overtime hours', max_digits=5),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='PRESENT', max_length=10),
        ),
    ]
