# Generated by Django 5.2.9 on 2025-12-04 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_has_ot_attendance_updated_at_and_more'),
        ('employees', '0002_employee_gatepass_number_employee_ot_per_hour_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='attendance_date_d460ba_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'date'], name='attendance_employe_c9bb2b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='attendance_status_a068a7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['marked_by'], name='attendance_marked__917650_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['-date', 'employee'], name='attendance_date_ed3dcd_idx'),
        ),
    ]
