# Generated by Django 5.2.9 on 2025-12-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_edited_at_attendance_edited_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='ot_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of overtime hours', max_digits=5, null=True),
        ),
    ]
